objects=\
normalize_image_pair.o\
gaussian_blur_image.o\
downsample_image_dimensions.o\
downsample_image.o\
warp_image.o\
image_derivative_x.o\
image_derivative_y.o\
update_displacement.o\
upsample_image.o\
psi_prime_smooth.o\
psi_prime_smooth_1234.o\
divergence_gradient_u.o\
divergence_gradient_v.o\
psi_prime_data.o\
sor_iteration.o\
normalize_image.o\
normalize_image_dbl.o\
brox_optic_flow.o\
brox_optic_flow_main.o\
psi_prime_gradient.o\
equation_du_dv.o\
compute_disparity_map.o
